### ISSUE TITLE
Persistently errors out on one particular image.

### ISSUE THREAD

**Issue by egypturnash** [Xerbo/furaffinity-dl#67]
If I have https://www.furaffinity.net/view/45842186/ (NSFW, cw: hyper titties, clothed) in my favorites, the Python downloader will crash with the following error when it comes to this image:

```
Traceback (most recent call last):
  File "/Users/egypt/Documents/scripts/fa/peggy faves/../furaffinity-dl.py", line 202, in <module>
    download(img.find('a').attrs.get('href'))
  File "/Users/egypt/Documents/scripts/fa/peggy faves/../furaffinity-dl.py", line 135, in download
    for tag in s.find(class_='tags-row').findAll(class_='tags'):
AttributeError: 'NoneType' object has no attribute 'findAll'
```

If I unfav this one particular image, the downloader will happily go past the point it occupied in my favorites; favorite it again and the downloader once again crashes when it comes to it. The downloader also has no problems grabbing other images by this artist.

**Comment by egypturnash** [comment]
A friend noted that the image in question has no tags, and I just had this error happen again on another image that also has no tags, so this bug report may actually be "fails on images with no tags". :)

**Comment by egypturnash** [comment]
Fixed by https://github.com/Xerbo/furaffinity-dl/pull/68 :)
